[project]
name = "rnn-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.4.1",
    "setuptools>=80.1.0",
    "tqdm>=4.67.1",
]
